-- Ajoute les colonnes nécessaires pour l'import des CSV dans les tables PostgreSQL
-- Table recettes
ALTER TABLE recettes
  ADD COLUMN IF NOT EXISTS "Num_BE_Caisse" TEXT,
  ADD COLUMN IF NOT EXISTS "Code_Rubrique" TEXT,
  ADD COLUMN IF NOT EXISTS "Motif_BE" TEXT,
  ADD COLUMN IF NOT EXISTS "Heure_e" TEXT,
  ADD COLUMN IF NOT EXISTS "Code_Service" TEXT,
  ADD COLUMN IF NOT EXISTS "Date_Entree1" TEXT,
  ADD COLUMN IF NOT EXISTS "MT_Chiffre_BE" TEXT,
  ADD COLUMN IF NOT EXISTS "Num_Auto_BE" TEXT,
  ADD COLUMN IF NOT EXISTS "SUPPRIM" TEXT,
  ADD COLUMN IF NOT EXISTS "Date_Entree" TEXT,
  ADD COLUMN IF NOT EXISTS "Recu_De" TEXT,
  ADD COLUMN IF NOT EXISTS "MT_Lttre_BE" TEXT;

-- Table depenses
ALTER TABLE depenses
  ADD COLUMN IF NOT EXISTS "Code_Service" TEXT,
  ADD COLUMN IF NOT EXISTS "Motif_Bs" TEXT,
  ADD COLUMN IF NOT EXISTS "Num_Auto_Bc" TEXT,
  ADD COLUMN IF NOT EXISTS "NBEO" TEXT,
  ADD COLUMN IF NOT EXISTS "MT_Chiffre_BS" TEXT,
  ADD COLUMN IF NOT EXISTS "Date_Sortie1" TEXT,
  ADD COLUMN IF NOT EXISTS "Num_BS_Caisse" TEXT,
  ADD COLUMN IF NOT EXISTS "Benef" TEXT,
  ADD COLUMN IF NOT EXISTS "Heure_s" TEXT,
  ADD COLUMN IF NOT EXISTS "Date_Sortie" TEXT,
  ADD COLUMN IF NOT EXISTS "MT_Lttre_BS" TEXT,
  ADD COLUMN IF NOT EXISTS "SUPPRIM" TEXT,
  ADD COLUMN IF NOT EXISTS "Code_Rubrique" TEXT,
  ADD COLUMN IF NOT EXISTS "COD" TEXT;

-- Table rubriques
ALTER TABLE rubriques
  ADD COLUMN IF NOT EXISTS "Code_Rubrique" TEXT,
  ADD COLUMN IF NOT EXISTS "Rubrique" TEXT,
  ADD COLUMN IF NOT EXISTS "Imputation" TEXT,
  ADD COLUMN IF NOT EXISTS "Type" TEXT;
