// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  fetch: async (input, init) => {
    const token = localStorage.getItem('local_auth_token');
    const headers = new Headers(init?.headers);

    if (token) {
      headers.set('x-session-token', token);
    }

    const initWithHeaders = {
      ...init,
      headers,
    };

    return fetch(input, initWithHeaders);
  },
});